---
Name: cmspreviewpreference
After: 
  - "silverstripe/framework/*"
---
WebbuildersGroup\CMSPreviewPreference\Extensions\UserPreviewPreference:
  DefaultMode: "content"


SilverStripe\Admin\LeftAndMain:
  extensions:
    - 'WebbuildersGroup\CMSPreviewPreference\Extensions\CMSPreviewPreference'


SilverStripe\Security\Member:
  extensions:
    - 'WebbuildersGroup\CMSPreviewPreference\Extensions\UserPreviewPreference'